
language: node_js

node_js:
  - 8

os:
  - linux

cache:
  directories:
    - ${HOME}/.esy

install:
  - npm install --global esy@latest
  - esy install

script:
  - ( while true; do echo 'Compilation takes a while: keeping Travis alive.'; sleep 60; done ) & esy

