
language: perl

os:
  - linux

cache:
  directories:
    - ${HOME}/.esy

install:
  - cpanm Capture::Tiny
  - npm install --global esy@0.6.10 # esy@latest
  - esy install

script:
  - utilities/travis_hook.sh
  - utilities/test.pl

