
language: perl

perl:
  - "5.26"

os:
  - linux

cache:
  directories:
    - ${HOME}/.esy

install:
  - cd utilities/ ; cpanm --installdeps . ; cd ..
  - npm install --global esy@0.6.10 # esy@latest
  - esy install

script:
  - utilities/travis_hook.sh
  - utilities/test.pl

