
language: perl

perl:
  - "5.26"

os:
  - linux

cache:
  directories:
    - ${HOME}/.esy

install:
  - cpanm --local-lib=~/perl5 local::lib
  - eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --installdeps --notest .
  - npm install --global esy@0.6.10 # esy@latest
  - esy install

script:
  - utilities/travis_hook.sh

